### ISSUE TITLE
[Feature Request] 添加旧站点路径的重定向

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/danxi-dev.github.io#2]
现在我们仍在各处（如客户端、网页前端）使用旧的路径（如 `https://danxi.fduhole.com/about` 等），然而新的主页将这些内容放到了别处，直接访问会导致 404。

应该暂时添加重定向，减少用户看到 404 的频率。

参考：<https://github.com/DanXi-Dev/danxi-website-old/blob/source/src/router/index.ts>

**Comment by KYLN24** [comment]
目前有这些链接需要重定向：

- `/version` -> `https://github.com/DanXi-Dev/DanXi/releases`
- `/privacy` -> `/doc/app-privacy`
- `/terms-and-condition` -> `/doc/app-terms-and-condition`
- `/support` -> `https://danxi-dev.feishu.cn/wiki/wikcnrPPGDCiTODBYRkdwLlHH65`
- `/about` -> `/`

**Comment by KYLN24** [comment]
dd一下，一会儿就改
